/**
 * Writes the package version into src/generated/version.ts so the app can
 * display its own build version. CRA's ModuleScopePlugin forbids importing
 * package.json from src/, so we generate a small in-scope module instead.
 * Runs via the prestart/prebuild npm hooks.
 */
const fs = require('fs');
const path = require('path');

const pkg = require(path.join(__dirname, '..', 'package.json'));
const outDir = path.join(__dirname, '..', 'src', 'generated');
const outFile = path.join(outDir, 'version.ts');

const contents = `// AUTO-GENERATED by scripts/gen-version.js — do not edit.
export const UI_VERSION = ${JSON.stringify(pkg.version)};
`;

fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(outFile, contents);
console.log(`gen-version: wrote UI_VERSION=${pkg.version} to ${path.relative(process.cwd(), outFile)}`);
